In [1]:
import numpy as np

In [9]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr2 = np.arange(11, 21)

In [8]:
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr + arr2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [11]:
arr3 = arr

In [16]:
arr3

array([    1,     2,     3,   200,     5,     6,     7,     8, 12345,
          10])

In [17]:
arr

array([    1,     2,     3,   200,     5,     6,     7,     8, 12345,
          10])

In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'